### ISSUE TITLE
Matlab crashes [Matlab+Windows]

### ISSUE THREAD

**Issue by gpipelee** [meco-group/cpp_splines#43] opened 2016-10-12 15:00 UTC
I guess every time a function is called that is not yet filled in properly, e.g. 

```
m = SubMonomialBasis(degree);
sbv = SubBasisVector();
sbv.append(m);
sbv.append(m);
b = Basis.Basis(sbv);
```
- `b.castBSpline` causes a Matlab crash
- `b.getSubArgument(i)` causes a Matlab crash for every `i`
- ...

**Comment by jgillis** [comment] 2016-10-31 12:42
Caused by missing return statements. Since compiler warnings have been added; this should be fixed.

**Closed by jgillis** 2016-10-31 12:42 UTC
Labels: Crash
